- hosts: localhost
  become: true
  tasks:
    - include_tasks: "tasks/check_uefi.yml"
      verbosity: 3  # Nasconde l'output a meno che non venga eseguito con -vvv
  vars_files:
    - vars/main.yml

  roles:
    - role: setup