- hosts: localhost
  become: true
  tasks:
    - block:
        - name: "Check if system is in UEFI mode"
          stat:
            path: /sys/firmware/efi
          register: uefi_mode
          changed_when: false
          no_log: true  # Nasconde completamente l'output del task di controllo

        - name: "Ensure the system is in UEFI mode"
          assert:
            that:
              - uefi_mode.stat.exists is defined and uefi_mode.stat.exists == true
            fail_msg: "This playbook requires UEFI, but the system is running in BIOS/Legacy mode."
      rescue:
        - name: "Fail if the system is not in UEFI mode"
          fail:
            msg: "This playbook requires UEFI, but the system is running in BIOS/Legacy mode."
  vars_files:
    - vars/main.yml

  roles:
    - role: setup