---
- name: Check if system is in UEFI mode
  stat:
    path: /sys/firmware/efi
  register: uefi_mode

- fail:
    msg: "This playbook requires UEFI, but the system is running in BIOS/Legacy mode."
  when: uefi_mode.stat.exists is not defined or uefi_mode.stat.exists == false
