---
- block:
  - stat:
      path: /sys/firmware/efi
     register: uefi_mode
     changed_when: false  # Evita che il task venga considerato "changed"

  - fail:
      msg: "This playbook requires UEFI, but the system is running in BIOS/Legacy mode."
    when: uefi_mode.stat.exists is not defined or uefi_mode.stat.exists == false
  name: Check if system is in UEFI mode
