---
- name: Update pacman.conf with custom settings
  when: pacman.color == true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^#Color"
    line: "Color\nILoveCandy"
    state: present

- name: Enable verbose package lists
  when: pacman.verbose_pkg_lists == true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^#VerbosePkgLists"
    line: "VerbosePkgLists"
    state: present

- name: Enable parallel downloads
  when: pacman.parallel_download.enable == true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "^#ParallelDownloads"
    line: "ParallelDownloads = {{ pacman.parallel_download.number }}"
    state: present

- name: Refresh package database
  ansible.builtin.command: "pacman -Syy"
  ignore_errors: yes
